name: Build and Deploy

on:
  push:
    branches:
      - develop
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  Build:
    runs-on: ubuntu-latest
    # Run if it's a push OR if it's a merged pull request
    if: |
      github.event_name == 'push' || 
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - run: npm ci
      - run: npm run build

      - name: Upload Release
        uses: actions/upload-artifact@v4
        with:
          name: Release
          path: dist

  Publish:
    needs: Build
    runs-on: ubuntu-latest
    # No extra branch check needed here because the 'on' trigger already filters for 'develop'
    steps:
      - uses: actions/checkout@v4

      - name: Get Dist folder
        uses: actions/download-artifact@v4
        with:
          name: Release
          path: dist

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
